"""Regenerate the course's syntax-highlighting artifacts from capstone.

Instruction, register, condition-code and shift/extend-keyword lists are
extracted from capstone (the same disassembler the grader uses) rather than
written by hand. One run regenerates, from a single source:

- course/clientFilesCourse/ace/mode/mode-assembly_arm64.js
- course/clientFilesCourse/ace/mode/mode-assembly_arm32.js
- course/clientFilesCourse/ace/mode/mode-assembly_x86.js
- the GENERATED block in course/elements/asm-code/asm-code.py

Run from the repository root (requires capstone: pip install capstone):

    python -m util generate_highlighting

Before anything is written, the generated patterns are checked against every
```asm fence in EXEMPLAR_SOLUTIONS.md plus a per-architecture smoke set, so
extraction gaps fail loudly instead of silently un-highlighting code.
"""

import json
import re
from pathlib import Path

ACE_MODE_DIR = Path("course/clientFilesCourse/ace/mode")
ELEMENT_CONTROLLER = Path("course/elements/asm-code/asm-code.py")
EXEMPLAR = Path("EXEMPLAR_SOLUTIONS.md")

BEGIN_MARKER = (
    "# BEGIN GENERATED (python -m util generate_highlighting) -- do not edit by hand"
)
END_MARKER = "# END GENERATED"

GENERATED_JS_HEADER = (
    "// GENERATED by 'python -m util generate_highlighting' -- do not edit by hand.\n"
    "// Instruction/register lists are extracted from capstone's {arch} enumerations.\n"
)

# Capstone const-module candidates per architecture (capstone >= 6 renames
# arm64 to aarch64; scanning is by name so both spellings work).
CONST_MODULES = {
    "arm64": ["arm64", "aarch64"],
    "arm32": ["arm"],
    "x64": ["x86"],
}

# Non-enumerable extras; kept small and visible. Everything else comes from
# capstone.
X64_OPERAND_KEYWORDS = [
    "byte", "word", "dword", "qword", "tbyte",
    "xmmword", "ymmword", "zmmword", "ptr", "offset", "short",
]
X64_PREFIX_MNEMONICS = ["lock", "rep", "repe", "repz", "repne", "repnz", "notrack"]
ARM64_ARRANGEMENTS = [
    "16b", "8b", "8h", "4h", "4s", "2s", "2d", "1d", "1q", "b", "h", "s", "d",
]
CC_ALIASES = {"cs": "hs", "hs": "cs", "cc": "lo", "lo": "cc"}
EXCLUDED_SUFFIXES = {"invalid", "ending"}

# Sanity expectations (guards against extracting from the wrong enum, not a
# source of highlighting data).
SMOKE = {
    "arm64": {
        "mnemonics": ["add", "adds", "subs", "ldr", "stp", "udiv", "ret", "b", "b.ne", "mov"],
        "registers": ["x0", "x30", "w30", "xzr", "wzr", "sp", "lr", "fp", "v0", "v7.8b", "q0"],
        "operand_keywords": ["lsl", "sxtw", "ge"],
    },
    "arm32": {
        "mnemonics": ["add", "adds", "addseq", "add.w", "push", "pop", "ldm", "bx", "movweq"],
        "registers": ["r0", "r12", "sp", "lr", "pc", "ip"],
        "operand_keywords": ["lsl", "rrx", "eq"],
    },
    "x64": {
        "mnemonics": ["mov", "movzx", "lea", "jmp", "add", "rep"],
        "registers": ["rax", "eax", "ax", "al", "bl", "r15b", "r10d", "rip"],
        "operand_keywords": ["byte", "qword", "ptr"],
    },
}

# Register shapes used only by the exemplar self-check to recognize tokens
# that must be matched by the generated register patterns.
REGISTER_SHAPES = {
    "arm64": r"\b(?:[xw]\d+|xzr|wzr|sp|lr|fp)\b",
    "arm32": r"\b(?:r\d+|sp|lr|pc|ip)\b",
    "x64": r"\b(?:[re]?[abcd]x|[abcd][lh]|[re]?(?:si|di|bp|sp|ip)|sil|dil|bpl|spl|r\d+[dwb]?)\b",
}


def _const_suffixes(module, prefix: str, midfix: str) -> set[str]:
    full = f"{prefix}_{midfix}_"
    return {
        name[len(full):].lower() for name in dir(module) if name.startswith(full)
    } - EXCLUDED_SUFFIXES


def _load_arch_consts(module_names: list[str]):
    import importlib

    for module_name in module_names:
        try:
            module = importlib.import_module(f"capstone.{module_name}_const")
        except ImportError:
            continue
        prefix = module_name.upper()
        if _const_suffixes(module, prefix, "INS"):
            return module, prefix
    raise RuntimeError(
        f"No usable capstone const module among {module_names} - is capstone installed?"
    )


def _alternation(items) -> str:
    """Longest-first non-capturing alternation body for a set of literals."""
    return "|".join(re.escape(item) for item in sorted(items, key=lambda s: (-len(s), s)))


def _build_patterns() -> dict[str, dict[str, str]]:
    patterns = {}

    for arch, module_names in CONST_MODULES.items():
        module, prefix = _load_arch_consts(module_names)

        mnemonics = _const_suffixes(module, prefix, "INS")
        registers = _const_suffixes(module, prefix, "REG")
        condition_codes = _const_suffixes(module, prefix, "CC")
        condition_codes |= {
            CC_ALIASES[cc] for cc in condition_codes & CC_ALIASES.keys()
        }
        shifts = {
            name.removesuffix("_reg")
            for name in _const_suffixes(module, prefix, "SFT")
            | _const_suffixes(module, prefix, "EXT")
        } - EXCLUDED_SUFFIXES

        if arch == "arm64":
            # Vector registers take an optional arrangement suffix (v0.8b) or
            # element accessor (v0.s[1] - the [1] is tokenized as brackets).
            vector = {r for r in registers if re.fullmatch(r"[vz]\d+", r)}
            arrangement = "|".join(ARM64_ARRANGEMENTS)
            register_pattern = (
                rf"(?:{_alternation(vector)})(?:\.(?:{arrangement}))?"
                rf"|{_alternation(registers - vector)}"
            )
            # Conditional branches (b.ne) are encoded as B + a condition code,
            # and flag-setting forms (adds) as ADD + update-flags detail, so
            # neither appears in the instruction enum; compose them here.
            mnemonic_pattern = (
                rf"b\.(?:{_alternation(condition_codes)})"
                rf"|(?:{_alternation(mnemonics)})s?"
            )
            operand_keyword_pattern = _alternation(shifts | condition_codes)
        elif arch == "arm32":
            register_pattern = _alternation(registers)
            # UAL suffix order: mnemonic + optional S + optional condition +
            # optional Thumb width qualifier (e.g. addseq.w). IT blocks encode
            # their then/else pattern as structural suffixes (ittee), like
            # b.cond on arm64, so they also need composing.
            mnemonic_pattern = (
                rf"it[te]{{0,3}}"
                rf"|(?:{_alternation(mnemonics)})"
                rf"s?(?:{_alternation(condition_codes)})?(?:\.[wn])?"
            )
            operand_keyword_pattern = _alternation(shifts | condition_codes)
        else:  # x64
            register_pattern = _alternation(registers)
            mnemonic_pattern = _alternation(mnemonics | set(X64_PREFIX_MNEMONICS))
            operand_keyword_pattern = _alternation(X64_OPERAND_KEYWORDS)

        if len(mnemonics) < 200 or len(registers) < 30:
            raise RuntimeError(
                f"{arch}: implausibly small extraction "
                f"({len(mnemonics)} mnemonics, {len(registers)} registers)"
            )

        patterns[arch] = {
            "mnemonics": mnemonic_pattern,
            "registers": register_pattern,
            "operand_keywords": operand_keyword_pattern,
            "mnemonic_count": len(mnemonics),
            "register_count": len(registers),
        }

    return patterns


def _smoke_check(patterns: dict) -> None:
    failures = []
    for arch, expectations in SMOKE.items():
        for kind, samples in expectations.items():
            pattern = re.compile(f"(?:{patterns[arch][kind]})", re.IGNORECASE)
            failures += [
                f"{arch}: {kind} pattern does not match {sample!r}"
                for sample in samples
                if not pattern.fullmatch(sample)
            ]
    if failures:
        raise RuntimeError("smoke check failed:\n  " + "\n  ".join(failures))


def _strip_comments(line: str, arch: str, in_block: bool) -> tuple[str, bool]:
    out = []
    i = 0
    while i < len(line):
        if in_block:
            end = line.find("*/", i)
            if end == -1:
                return "".join(out), True
            i = end + 2
            in_block = False
            continue
        if line.startswith("/*", i):
            in_block = True
            i += 2
            continue
        if line.startswith("//", i):
            break
        if arch == "arm32" and line[i] == "@":
            break
        if arch == "x64" and line[i] == "#":
            break
        out.append(line[i])
        i += 1
    return "".join(out), in_block


def _exemplar_check(patterns: dict) -> int:
    """Check every ```asm fence in the exemplar solutions against the
    generated patterns. Returns the number of statements checked."""
    if not EXEMPLAR.exists():
        print(f"warning: {EXEMPLAR} not found, skipping exemplar check")
        return 0

    compiled = {
        arch: {
            kind: re.compile(f"(?:{arch_patterns[kind]})", re.IGNORECASE)
            for kind in ("mnemonics", "registers")
        }
        for arch, arch_patterns in patterns.items()
    }

    arch = None
    in_fence = False
    in_block = False
    checked = 0
    failures = []

    for line_number, raw in enumerate(
        EXEMPLAR.read_text(encoding="utf-8").splitlines(), start=1
    ):
        if not in_fence:
            if raw.startswith("## "):
                arch = raw[3:].strip().lower()
            elif raw.strip() == "```asm" and arch in patterns:
                in_fence = True
                in_block = False
            continue
        if raw.strip() == "```":
            in_fence = False
            continue

        code, in_block = _strip_comments(raw, arch, in_block)
        code = code.strip()
        label_match = re.match(r"[\w.$]+:\s*", code)
        if label_match:
            code = code[label_match.end():]
        if not code or code.startswith("."):
            continue

        word_match = re.match(r"[A-Za-z_][\w.]*", code)
        if not word_match:
            failures.append(f"{EXEMPLAR}:{line_number}: unparseable statement: {raw!r}")
            continue
        checked += 1

        word = word_match.group(0)
        if not compiled[arch]["mnemonics"].fullmatch(word):
            failures.append(
                f"{EXEMPLAR}:{line_number}: {arch} mnemonic not matched: {word!r}"
            )

        operands = code[word_match.end():]
        for register in re.findall(REGISTER_SHAPES[arch], operands, re.IGNORECASE):
            if not compiled[arch]["registers"].fullmatch(register):
                failures.append(
                    f"{EXEMPLAR}:{line_number}: {arch} register not matched: {register!r}"
                )

    if failures:
        raise RuntimeError("exemplar check failed:\n  " + "\n  ".join(failures))
    if checked == 0:
        raise RuntimeError(f"exemplar check found no ```asm statements in {EXEMPLAR}")
    return checked


def _ace_rules(arch: str, arch_patterns: dict[str, str]) -> dict:
    mnemonics = arch_patterns["mnemonics"]
    start = []

    if arch == "arm32":
        start.append({"token": "comment", "regex": "@.*$"})
    if arch == "x64":
        start.append({"token": "comment", "regex": "#.*$"})

    start += [
        {"token": "comment", "regex": "\\/\\/.*$"},
        {"token": "comment", "regex": "\\/\\*", "next": "blockComment"},
        # A statement's first word (optionally after a label) is matched
        # against the known-mnemonic list; unknown first words stay plain.
        {
            "token": ["text", "entity.name.function", "text", "keyword"],
            "regex": f"^(\\s*)([\\w.$]+:)(\\s*)((?:{mnemonics}))(?=[\\s]|$)",
            "caseInsensitive": True,
        },
        {"token": ["text", "entity.name.function"], "regex": "^(\\s*)([\\w.$]+:)"},
        {
            "token": ["text", "keyword"],
            "regex": "^(\\s*)(\\.[A-Za-z_][\\w.]*)",
            "caseInsensitive": True,
        },
        {
            "token": ["text", "keyword"],
            "regex": f"^(\\s*)((?:{mnemonics}))(?=[\\s]|$)",
            "caseInsensitive": True,
        },
        {"token": ["text", "text"], "regex": "^(\\s*)([A-Za-z_][\\w.]*)"},
        {
            "token": "support.function",
            "regex": f"\\b(?:{arch_patterns['registers']})\\b",
            "caseInsensitive": True,
        },
        {
            "token": "keyword",
            "regex": f"\\b(?:{arch_patterns['operand_keywords']})\\b",
            "caseInsensitive": True,
        },
    ]

    if arch in ("arm64", "arm32"):
        start.append({
            "token": "constant.numeric",
            "regex": "#-?(?:0x[0-9a-f]+|0b[01]+|\\d+)\\b",
            "caseInsensitive": True,
        })

    start += [
        {
            "token": "constant.numeric",
            "regex": "\\b(?:0x[0-9a-f]+|0b[01]+|\\d+)\\b",
            "caseInsensitive": True,
        },
        {"token": "string", "regex": '"[^"]*"'},
        {"token": "string", "regex": "'[^']*'"},
        {"token": "keyword.operator", "regex": "[!+\\-*]"},
        {"token": "paren.lparen", "regex": "[\\[{]"},
        {"token": "paren.rparen", "regex": "[\\]}]"},
        {"token": "punctuation.operator", "regex": ","},
        {"token": "entity.name.function", "regex": "[A-Za-z_.$][\\w.$]*"},
        {"defaultToken": "text"},
    ]

    return {
        "start": start,
        "blockComment": [
            {"token": "comment", "regex": "\\*\\/", "next": "start"},
            {"defaultToken": "comment"},
        ],
    }


ACE_MODES = {
    "arm64": ("assembly_arm64", "//"),
    "arm32": ("assembly_arm32", "@"),
    "x64": ("assembly_x86", "#"),
}

ACE_TEMPLATE = """\
{header}ace.define('ace/mode/{name}', [], function (require, exports, module) {{
  'use strict';

  var oop = require('ace/lib/oop');
  var TextMode = require('ace/mode/text').Mode;
  var TextHighlightRules = require('ace/mode/text_highlight_rules').TextHighlightRules;

  var HighlightRules = function () {{
    this.$rules = {rules};
  }};
  oop.inherits(HighlightRules, TextHighlightRules);

  var Mode = function () {{
    this.HighlightRules = HighlightRules;
  }};
  oop.inherits(Mode, TextMode);

  (function () {{
    this.lineCommentStart = '{line_comment}';
    this.blockComment = {{ start: '/*', end: '*/' }};
    this.$id = 'ace/mode/{name}';
  }}).call(Mode.prototype);

  exports.Mode = Mode;
}});
"""


def _write_ace_modes(patterns: dict) -> list[Path]:
    written = []
    for arch, (name, line_comment) in ACE_MODES.items():
        rules = json.dumps(_ace_rules(arch, patterns[arch]), indent=2)
        # Indent the rules object to sit inside the highlight-rules function.
        rules = rules.replace("\n", "\n    ")
        content = ACE_TEMPLATE.format(
            header=GENERATED_JS_HEADER.format(arch=arch),
            name=name,
            line_comment=line_comment,
            rules=rules,
        )
        path = ACE_MODE_DIR / f"mode-{name}.js"
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        written.append(path)
    return written


def _write_element_block(patterns: dict) -> None:
    controller = ELEMENT_CONTROLLER.read_text(encoding="utf-8")
    begin = controller.find(BEGIN_MARKER)
    end = controller.find(END_MARKER)
    if begin == -1 or end == -1 or end < begin:
        raise RuntimeError(f"GENERATED markers not found in {ELEMENT_CONTROLLER}")

    block_lines = [BEGIN_MARKER]
    for arch in ("arm64", "arm32", "x64"):
        prefix = arch.upper()
        for kind in ("mnemonics", "registers", "operand_keywords"):
            block_lines.append(f"{prefix}_{kind.upper()} = {patterns[arch][kind]!r}")
    block = "\n".join(block_lines) + "\n"

    controller = controller[:begin] + block + controller[end:]
    with open(ELEMENT_CONTROLLER, "w", encoding="utf-8", newline="\n") as f:
        f.write(controller)


def generate_highlighting() -> None:
    if not ACE_MODE_DIR.is_dir() or not ELEMENT_CONTROLLER.exists():
        raise RuntimeError("run from the repository root (course/ not found)")

    patterns = _build_patterns()
    _smoke_check(patterns)
    checked = _exemplar_check(patterns)

    written = _write_ace_modes(patterns)
    _write_element_block(patterns)

    for arch in CONST_MODULES:
        print(
            f"{arch}: {patterns[arch]['mnemonic_count']} mnemonics, "
            f"{patterns[arch]['register_count']} registers"
        )
    print(f"exemplar check: {checked} statements verified")
    for path in written:
        print(f"wrote {path}")
    print(f"updated {ELEMENT_CONTROLLER} (generated block)")
